In [1]:
import numpy as np

In [2]:
a = np.random.randn(2, 3) # a.shape = (2, 3)
b = np.random.randn(2, 1) # b.shape = (2, 1)
c = a + b

In [6]:
print(a)
print()
print(b)
print()
print(c)
print()

[[-1.16439222 -1.07442679 -1.67443487]
 [-0.5100573   0.13970424 -0.15295018]]

[[-0.77222325]
 [ 0.67031526]]

[[-1.93661547 -1.84665004 -2.44665812]
 [ 0.16025796  0.8100195   0.51736508]]



In [4]:
c.shape

(2, 3)

In [8]:
a = np.random.randn(4, 3) # a.shape = (4, 3)
b = np.random.randn(3, 2) # b.shape = (3, 2)

In [9]:
print(a)
print()
print(b)

[[ 0.78241353  0.78705334  0.8496721 ]
 [ 0.3694177  -0.18473807 -0.94124843]
 [ 0.39923954  0.45843871 -0.03104892]
 [-0.00844559  0.59651956  1.49327578]]

[[-0.17582246  0.17699802]
 [-0.18296451 -1.53692791]
 [-0.09461072  0.77227364]]


In [10]:
c = a*b

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [11]:
# a.shape = (3,4)
# b.shape = (4,1)
a = np.random.randn(3, 4)
b = np.random.randn(4, 1)

In [13]:
a

array([[-0.82101655,  1.41372213, -2.0201995 ,  0.27018865],
       [-0.92026984, -0.14739612,  1.19404125,  0.88496421],
       [ 0.51082588,  0.31326728, -1.17663762, -0.78025104]])

In [20]:
b.T

array([[ 0.60467044, -0.1560648 , -0.0428051 ,  1.84292311]])

In [16]:
for i in range(3):
    for j in range(4):
        c[i][j] = a[i][j] + b[i]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [21]:
a+b.T

array([[-0.21634611,  1.25765732, -2.0630046 ,  2.11311176],
       [-0.3155994 , -0.30346092,  1.15123615,  2.72788732],
       [ 1.11549633,  0.15720248, -1.21944272,  1.06267207]])

In [22]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)

In [23]:
a

array([[-0.48765533, -0.57001715,  0.98173322],
       [-0.82419453, -1.48937613,  1.15256457],
       [-0.39572461,  0.71126381,  0.646665  ]])

In [24]:
b

array([[0.60337066],
       [0.08942948],
       [0.17171239]])

In [26]:
a*b

array([[-0.29423692, -0.34393162,  0.59234902],
       [-0.07370729, -0.13319413,  0.10307325],
       [-0.06795082,  0.12213281,  0.11104039]])

In [27]:
np.exp(3)

20.085536923187668

In [28]:
A = np.random.randn(4,3)
B = np.sum(A, axis = 1, keepdims = True)

In [30]:
B.shape

(4, 1)